CREATE TABLE  "AFTERDELIVERY" 
   (	"COUPLENO" NUMBER(10,0), 
	"LADYNAME" VARCHAR2(50), 
	"DELIVERYDATE" DATE, 
	"DELIVERYPLACE" VARCHAR2(50), 
	"DELIVERYTYPE" VARCHAR2(50), 
	"PRAGNANCEY" VARCHAR2(30), 
	"HOSPITALPEROID" VARCHAR2(30), 
	"KIDGENDER" VARCHAR2(20), 
	"KIDCRYAFTERBORN" VARCHAR2(30), 
	"KIDWEIGHT" NUMBER(10,0), 
	"HOSPITALDECHARGEDATE" DATE, 
	"DELIVERYRESULT" VARCHAR2(30), 
	"HOPE" NUMBER, 
	"PROBLEM" VARCHAR2(4000), 
	 FOREIGN KEY ("COUPLENO")
	  REFERENCES  "MOTHERTABLE" ("COUPLENO") ENABLE
   )
