CREATE TABLE  "AGGANWARITABLE" 
   (	"AGGANID" VARCHAR2(30), 
	"AGGANREGNO" VARCHAR2(10), 
	"RGDATE" DATE, 
	"UPPERCENTER" NUMBER(10,0), 
	"CENDATE" DATE, 
	"ASHA" VARCHAR2(50), 
	"ANM" VARCHAR2(50), 
	"UPPERHC" VARCHAR2(100), 
	"FHC" VARCHAR2(100), 
	"HOSFRU" VARCHAR2(100), 
	"CONTECTNO" NUMBER(13,0), 
	"EMAIL" VARCHAR2(50), 
	"PASSWORD" VARCHAR2(50), 
	"CENTER" VARCHAR2(50), 
	"OWNER" VARCHAR2(50), 
	 PRIMARY KEY ("AGGANID") ENABLE
   )
