CREATE TABLE  "MOTHERTABLE" 
   (	"AGGANID" VARCHAR2(30), 
	"COUPLENO" NUMBER(10,0), 
	"PLNAME" VARCHAR2(50), 
	"HUSNAME" VARCHAR2(50), 
	"BDATE" DATE, 
	"EDUCATION" VARCHAR2(50), 
	"ADDRESS" VARCHAR2(100), 
	"CITY" VARCHAR2(50), 
	"STATE" VARCHAR2(50), 
	"DIST" VARCHAR2(50), 
	"MOBNO" NUMBER(13,0), 
	"CITYPIN" NUMBER(10,0), 
	"TOTALCHILD" NUMBER(10,0), 
	"JSIREGNO" NUMBER(10,0), 
	"JSIPAIDMON" NUMBER(10,0), 
	"JSIDATE" DATE, 
	"PHOTO" VARCHAR2(4000), 
	 PRIMARY KEY ("COUPLENO") ENABLE, 
	 FOREIGN KEY ("AGGANID")
	  REFERENCES  "AGGANWARITABLE" ("AGGANID") ENABLE
   )
